
# キャラとそのメモリーピースのPNGとを紐付けるマスタ的な
CHARACTOR_PNG = {
  "★★★アンナ": 'anna_crop.PNG',
  "★★★マホ": 'maho_crop.PNG',
  "★★★リノ": 'rino_crop.PNG',
  "★★★ハツネ": 'hatsune_crop.PNG',
  "★★★イオ": 'io_crop.PNG',
  "★★★サレン": 'saren_crop.PNG',
  "★★★ノゾミ": 'nozomi_crop.PNG',
  "★★★ニノン": 'ninon_crop.PNG',
  "★★★アキノ": 'akino_crop.PNG',
  "★★★マコト": 'makoto_crop.PNG',
  "★★★シズル": 'shizuru_crop.PNG',
  "★★★モニカ": 'monica_crop.PNG',
  "★★★ジータ": 'jiita_crop.PNG',
  "★★★アリサ": 'arisa_crop.PNG',
  "★★★ジュン": 'jun_crop.PNG',
  "★★★ペコリーヌ_夏": 'peco_summer_crop.PNG',
  "★★★キョウカ": 'kyouka_crop.PNG',
  "★★★イリヤ": 'iriya_crop.PNG',
  "★★★キャル": 'kyaru_summer_crop.PNG',
#  "★★★スズメ_夏": 'suzume_summer_crop.PNG',
  "★★アカリ": 'akari_crop.PNG',
  "★★ミヤコ": 'miyako_crop.PNG',
  "★★アヤネ": 'ayane_crop.PNG',
  "★★ユキ": 'yuki_crop.PNG',
  "★★スズナ": 'suzuna_crop.PNG',
  "★★カオリ": 'kaori_crop.PNG',
  "★★ミミ": 'mimi_crop.PNG',
  "★★エリコ": 'eriko_crop.PNG',
  "★★シノブ": 'shinobu_crop.PNG',
  "★★マヒル": 'mahiru_crop.PNG',
  "★★シオリ": 'shiori_crop.PNG',
  "★★チカ": 'tika_crop.PNG',
  "★★クウカ": 'kuuka_crop.PNG',
  "★★タマキ": 'tamaki_crop.PNG',
  "★★ミフユ": 'mihuyu_crop.PNG',
  "★★ミツキ": 'mitsuki_crop.PNG',
  "★★ミサト": 'misato_crop.PNG',
  "★★リン": 'rin_crop.PNG',
  "★★ツムギ": 'tsumugi_crop.PNG',
  "★ヒヨリ": 'hiyori_crop.PNG',
  "★レイ": 'rei_crop.PNG',
  "★ミソギ": 'misogi_crop.PNG',
  "★クルミ": 'kurumi_crop.PNG',
  "★ヨリ": 'yori_crop.PNG',
  "★スズメ": 'suzume_crop.PNG',
  "★ユカリ": 'yukari_crop.PNG',
  "★アオイ": 'aoi_crop.PNG',
  "★ミサキ": 'misaki_crop.PNG',
  "★リマ": 'rima_crop.PNG',
  "★ペコリーヌ": 'pecorine_crop.PNG',
  "★コッコロ": 'coccoro_crop.PNG',
  "★キャル": 'kyaru_crop.PNG',
  "★ユイ": 'yui_crop.PNG'
#  "★ミフユ_夏": 'mihuyu_summer_crop.PNG',
#  "★コッコロ_夏": 'coccoro_summer_crop.PNG',
}
